### ISSUE TITLE
Not providing --dummy parameter throws stack trace on dummy status

### ISSUE THREAD

**Issue by gordysc** [vinli/vinli-cli#3]
I entered the following command expecting to get the status of a dummy device, but got a stack trace instead:

lukes-MacBook-Pro: gordysc$ vinli dummy status bc3a6395-7d14-4110-b2d2-e009f40d25ac
```
Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at forEach (/usr/local/lib/node_modules/vinli-cli/node_modules/Levenshtein/lib/levenshtein.js:15:19)
    at new Levenshtein (/usr/local/lib/node_modules/vinli-cli/node_modules/Levenshtein/lib/levenshtein.js:53:7)
    at /usr/local/lib/node_modules/vinli-cli/lib/fuzzy_find.js:19:19
    at arrayMap (/usr/local/lib/node_modules/vinli-cli/node_modules/lodash/lodash.js:604:23)
    at Function.map (/usr/local/lib/node_modules/vinli-cli/node_modules/lodash/lodash.js:7929:14)
    at /usr/local/lib/node_modules/vinli-cli/lib/fuzzy_find.js:18:25
    at tryCatcher (/usr/local/lib/node_modules/vinli-cli/node_modules/yarp/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/vinli-cli/node_modules/yarp/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/vinli-cli/node_modules/yarp/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/vinli-cli/node_modules/yarp/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/vinli-cli/node_modules/yarp/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/vinli-cli/node_modules/yarp/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/vinli-cli/node_modules/yarp/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I didn't see anything on the documentation page, but looking at the source code it appears we need to specify a --dummy flag (which in hindsight is obvious).  Can we add that check in? I can do a pull request for this if you'd like.

**Comment by gangstead** [comment]
Fixed in f06a5f92
