### ISSUE TITLE
In Windows, executing commands in certain directories cause errors

### ISSUE THREAD

**Issue by Kahtaf** [vinli/vinli-cli#7]
Found this issue using Windows 7 64 bit. When executing any command in the "C:\Users\alamka" directory, it produces this stack trace. However, it works just fine if I execute the same command while in "C:\Users". 

```
C:\Users\alamka>vinli auth authorize
C:\Users\alamka\AppData\Roaming\npm\node_modules\vinli-cli\lib\vinlirc.js:34
    ? _.filter(paths, (p) => p.search(home) === 0)
                               ^

SyntaxError: Invalid regular expression: /C:\Users\alamka\/: \ at end of pattern
    at new RegExp (native)
    at String.search (native)
    at C:\Users\alamka\AppData\Roaming\npm\node_modules\vinli-cli\lib\vinlirc.js:34:32
    at arrayFilter (C:\Users\alamka\AppData\Roaming\npm\node_modules\vinli-cli\node_modules\lodash\lodash.js:547:11)
    at Function.filter (C:\Users\alamka\AppData\Roaming\npm\node_modules\vinli-cli\node_modules\lodash\lodash.js:7596:14)
    at _.some.files (C:\Users\alamka\AppData\Roaming\npm\node_modules\vinli-cli\lib\vinlirc.js:34:9)
    at _.some.config (C:\Users\alamka\AppData\Roaming\npm\node_modules\vinli-cli\lib\vinlirc.js:65:17)
    at Object._.some.readConfig [as read] (C:\Users\alamka\AppData\Roaming\npm\node_modules\vinli-cli\lib\vinlirc.js:75:22)
    at Object.<anonymous> (C:\Users\alamka\AppData\Roaming\npm\node_modules\vinli-cli\bin\vinli-auth-authorize:118:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

**Comment by gangstead** [comment]
Welcome to our test program for the Windows platform!  Just kidding.  I'll find a windows machine to test against.

**Comment by gangstead** [comment]
Please update to version `v1.1.4` and verify that it is fixed.  I was able to recreate the problem on a Windows 10 64bit laptop and verify the fix from there.

**Comment by gangstead** [comment]
If `v1.1.4` does not fix the issue for you please reopen.

**Comment by Kahtaf** [comment]
Works! Thanks.
