### ISSUE TITLE
Error: Cannot find module 'Levenshtein' after "npm install -g"

### ISSUE THREAD

**Issue by sandro-csimas** [vinli/vinli-cli#8]
After:
````
npm install -g vinli-cli
````
When I execute (or any other command):
````
vinli device list 
````
This error happens:
````
sandro@EISABA-NT0024:~$ vinli 
module.js:442
    throw err;
    ^

Error: Cannot find module 'Levenshtein'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sandro/tools/node-v6.2.2-linux-x64/lib/node_modules/vinli-cli/lib/fuzzy_find.js:4:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
````

**Comment by sandro-csimas** [comment]
Looking at the source code of 
````/home/sandro/tools/node-v6.2.2-linux-x64/lib/node_modules/vinli-cli/lib/fuzzy_find.js:4:21````
I think the dependency name should be in lower case
````
require('Levenshtein'); -> require('levenshtein');
````

**Comment by gangstead** [comment]
I can fix that. I'm trying to recreate it to make sure that fixes it.  It was working when it was developed on Node 4. It looks like you are on linux using Node 6.2.2., is that right?  What version of npm?

I'm trying it on a OSX with node v6.2.2 (npm v3.9.5) and node v6.4.0 (npm v3.10.3) and not having the problem.

**Comment by sandro-csimas** [comment]
Yes, Linux.
````
$ npm -v
3.9.5
$ node -v
v6.2.2
`````

**Comment by gangstead** [comment]
Looks like linux is more strict when resolving file names.  I just published `vinli-cli@1.1.6` can you update and try again?

**Comment by sandro-csimas** [comment]
@gangstead, now its working fine, thanks!

**Comment by gangstead** [comment]
Thanks for reporting the issue.  I'm going to email you about sending some Vinli stickers your way.
